sudo: required
language: generic
services:
- docker
script:
- docker ps -a
- ENVIRONMENT=integration docker-compose -p grandlyon up -d
before_install:
- openssl aes-256-cbc -K $encrypted_4551da0a6112_key -iv $encrypted_4551da0a6112_iv
  -in integration/docker-certs/server-key.pem.enc -out integration/docker-certs/server-key.pem
  -d
- openssl aes-256-cbc -K $encrypted_4551da0a6112_key -iv $encrypted_4551da0a6112_iv
  -in integration/docker-certs/key.pem.enc -out integration/docker-certs/key.pem -d
