sudo: required

language: generic

services:
  - docker

script:
  - curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine
  - sudo install /tmp/docker-machine /usr/local/bin/docker-machine